### ISSUE TITLE
github为什么搞这个，不应该传到文学相关的网站上。

### ISSUE THREAD

**Issue by gstsgy** [zealotCE/AmericaOpposeAmerica#22]

**Comment by luojunyuan** [comment]
因为github不是单纯的技术网站，开源社区

**Comment by Pengxn** [comment]
GitHub 官方自己都说github是 for coding but not only，很多东西都有，开源书籍很多GitHub 都有，还有awesome列表，甚至你的学习资料，论文备份

**Comment by gstsgy** [comment]
soga
