### ISSUE TITLE
github为什么搞这个，不应该传到文学相关的网站上??

### ISSUE THREAD

**Issue by LaTiaoDi** [zealotCE/AmericaOpposeAmerica#23]
github为什么搞这个，不应该传到文学相关的网站上???

**Comment by raymondyan** [comment]
GitHub is not mere a coding hub, Git is created for version control, not only for codes but everything.

**Comment by Pengxn** [comment]
你怕不是来杠的哟，GitHub 官方自己都说github是 for coding but not only，很多东西都有，开源书籍很多GitHub 都有，还有awesome列表，甚至你的学习资料，论文备份

**Comment by likeSo** [comment]
> 你怕不是来杠的哟，GitHub 官方自己都说github是 for coding but not only，很多东西都有，开源书籍很多GitHub 都有，还有awesome列表，甚至你的学习资料，论文备份

不能同意更多，之前有人整理任正非语录的时候也有好多人说不能放，我寻思人家GitHub都不管，就像你说的一样，那些人跳出来不可笑吗？他们不觉得自己太自卑了吗？

**Comment by raymondyan** [comment]
> > 你怕不是来杠的哟，GitHub 官方自己都说github是 for coding but not only，很多东西都有，开源书籍很多GitHub 都有，还有awesome列表，甚至你的学习资料，论文备份
> 
> 不能同意更多，之前有人整理任正非语录的时候也有好多人说不能放，我寻思人家GitHub都不管，就像你说的一样，那些人跳出来不可笑吗？他们不觉得自己太自卑了吗？

在他们的 stereotypes 里，Github就是用来堆叠代码的，会说出这种话的人，如果说出类似“女人为什么出来上班，不应该在家里面洗衣做饭门么”的话也挺正常了

**Comment by cn247365** [comment]
请不要滥用这种权力，GitHub就是一个放源代码，程序员们的合作分享的地方，请少谈政治。珍惜这份自由

**Comment by DDCHlsq** [comment]
> 请不要滥用这种权力，GitHub就是一个放源代码，程序员们的合作分享的地方，请少谈政治。珍惜这份自由

谁和你谈政治了啊，少在这自作多情了，放本书管这么多？github自己都说不止放代码，省省吧您。

**Comment by likeSo** [comment]
> 请不要滥用这种权力，GitHub就是一个放源代码，程序员们的合作分享的地方，请少谈政治。珍惜这份自由

建议把这个评论到“天朝太子党图鉴”那个repo中去。污蔑讽刺我天朝官员的时候，你和我说这是自由。但是我放任正非语录，我放本书，你和我说GitHub不能放这些东西，让我珍惜自由。你真有意思，你们这群人真有意思

**Comment by Pickman-Model** [comment]
> 请不要滥用这种权力，GitHub就是一个放源代码，程序员们的合作分享的地方，请少谈政治。珍惜这份自由

程序员群体经常有你这种圈地自萌又自视甚高的行为艺术

**Comment by lsdlab** [comment]
> 请不要滥用这种权力，GitHub就是一个放源代码，程序员们的合作分享的地方，请少谈政治。珍惜这份自由

代码没写几行呢 还bb自由？你用得着GitHub吗？抄抄你同事的代码不就行了

**Comment by cn247365** [comment]
香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。

**Comment by lsdlab** [comment]
> 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。

那关我屁事？我照用不误。

**Comment by zhiqwang** [comment]
> 那关我屁事？我照用不误。

u1s1 这么说也不太合适吧

**Comment by likeSo** [comment]
> 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。

你告诉我这本书批评谁了？另外，你有到我说的那个repo中去看过么？你去批评过那个repo的作者么？你知道当初GitHub拒绝删除那个repo么？人家GitHub自己都说的可以放，你跳出来干什么？你感同身受了？

**Comment by lsdlab** [comment]
> > 那关我屁事？我照用不误。
> 
> u1s1 这么说也不太合适吧

是不关我的事啊，其他人怎么用GitHub我又不评论，用的不对有官方管，关我啥事儿啊

**Comment by zhiqwang** [comment]
> 香港会变成今天的样子就是因为一本书

这本书力量真大！

**Comment by Pickman-Model** [comment]
> 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。

我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？

**Comment by Wenzhi** [comment]
What's the freaking point of this issue? This is not what issue is for. This is not what Github is for. The whole thing is neither meaningful nor productive.

For new users, please checkout [Github community guideline](https://docs.github.com/en/github/site-policy/github-community-guidelines#building-a-strong-community) and act accordingly. Github is for collaborating project, no limit to codes or programs, absolutely not a forum for people to argue. Please don't forget, people can report misbehavior in Github as well. 

I strongly suggest the repo owner close/remove this issue. @zealotCE you have the power to stop this mess and please do.

**Comment by cn247365** [comment]
> > 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。
> 
> 我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？

我现在才发现原来是常委之一的王沪宁写。你觉得他真的有本事写书吗，习近平也出过很多书，你觉得他写得出来吗，7常委中共高层可以说没一个是有文化的，因为他们之中连脱稿演讲的能力都不具备，连脱稿回答记者的问题的能力都没有的人，还能写书。真搞不懂GitHub上面还有那么多仇恨抹黑美国的小粉红，大5毛。

**Comment by lsdlab** [comment]
抓不清重点的蠢逼真的多

**Comment by likeSo** [comment]
> > > 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。
> > 
> > 
> > 我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？
> 
> 我现在才发现原来是常委之一的王沪宁写。你觉得他真的有本事写书吗，习近平也出过很多书，你觉得他写得出来吗，7常委中共高层可以说没一个是有文化的，因为他们之中连脱稿演讲的能力都不具备，连脱稿回答记者的问题的能力都没有的人，还能写书。真搞不懂GitHub上面还有那么多仇恨抹黑美国的小粉红，大5毛。

我也搞不懂为什么有这么多双标狗，这群狗在遇到国内不喜欢的事物是，舔得十分积极，而遇到西方不喜欢得事物时，就开始说GitHub不应该放这种东西。甚至有激进分子（比如像您这种）开始戴帽子进行言语辱骂。怎么，就您自己有分辨是非的能力？众人皆醉你独醒？既然你开始不按章法乱咬，那您大可继续，我不骂到你祖坟爆炸就算你祖上无人。（阿弥陀佛，失礼了）

**Comment by chenshunyu** [comment]
> > > 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。
> > 
> > 
> > 我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？
> 
> 我现在才发现原来是常委之一的王沪宁写。你觉得他真的有本事写书吗，习近平也出过很多书，你觉得他写得出来吗，7常委中共高层可以说没一个是有文化的，因为他们之中连脱稿演讲的能力都不具备，连脱稿回答记者的问题的能力都没有的人，还能写书。真搞不懂GitHub上面还有那么多仇恨抹黑美国的小粉红，大5毛。好歹都是翻过墙的人，难道连这点分辨是否的能力都没有吗？还是故意，还想给程序员洗脑。

都2120年了，怎么还有人当公知？

**Comment by Pickman-Model** [comment]
我说一下我的想法，这本书《美国反对美国》，初看题目有点耸动标题党的感觉，但是实际内容是对80年代末美国的观察和思考，在最近几年突然火起来是因为书中提到的很多问题已经在美国变成现实，而中国也会经历或者正在经历这些问题，作为中国人在即将进入21世纪第三个十年不可能再通过阅读这本91年出版的书来观察美国，阅读的更多动力或者收获不在于批评现在的美国而在于借鉴反思自己，别人经历过的问题我们不反思不借鉴经验只会重蹈覆辙。希望讨论更多的着眼于文本内容而不是相互攻击屁股坐在哪里。

**Comment by zhiqwang** [comment]
> 我说一下我的想法，这本书《美国反对美国》，初看题目有点耸动标题党的感觉，但是实际内容是对80年代末美国的观察和思考，在最近几年突然火起来是因为书中提到的很多问题已经在美国变成现实，而中国也会遇到或者正在经历这些问题，作为中国人在即将进入21世纪第三个十年不可能再通过阅读这本91年出版的书来观察美国，阅读的更多动力或者收获不在于批评现在的美国而在于借鉴反思自己，别人经历过的问题我们不反思不借鉴经验只会重蹈覆辙。希望讨论更多的着眼于文本内容而不是相互攻击屁股坐在哪里。

说得很好，说“美国”重点还是想国内如何发展，如何发展得好，咱们也确实在面临着这些问题。

另外，我疑惑就是这本书的版权问题，如果版权没问题的话，这个项目其实很好，大家都合力把错别字改改，做一些网页也都是很好的项目。

**Comment by raymondyan** [comment]
> > > 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。
> > 
> > 
> > 我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？
> 
> 我现在才发现原来是常委之一的王沪宁写。你觉得他真的有本事写书吗，习近平也出过很多书，你觉得他写得出来吗，7常委中共高层可以说没一个是有文化的，因为他们之中连脱稿演讲的能力都不具备，连脱稿回答记者的问题的能力都没有的人，还能写书。真搞不懂GitHub上面还有那么多仇恨抹黑美国的小粉红，大5毛。好歹都是翻过墙的人，难道连这点分辨是否的能力都没有吗？还是故意，还想给程序员洗脑。

王沪宁的维基百科去看一看再说好不好？“三朝帝师”可不是瞎叫的

**Comment by DDCHlsq** [comment]
> > > 香港会变成今天的样子就是因为一本书，你们应该不会不知道吧。GitHub为什么在国内访问速度那么慢，也就是因为Github上很多批评中共的言论。被长城防火墙限流。如果还这样发一些很代码无关的东西，早晚也被会中共彻底封杀。
> > 
> > 
> > 我就不说其他的，就单单说这本来讲，你知道这书的作者现在是七常委之一吗？作为身居如此高位的人当年还是年轻学者时，去美国学术访问，观察记录思考而写就的一本书，并且时至今日在墙内豆瓣还有存有词条，在你眼里GitHub怎么就容不下这么一本书？
> 
> 我现在才发现原来是常委之一的王沪宁写。你觉得他真的有本事写书吗，习近平也出过很多书，你觉得他写得出来吗，7常委中共高层可以说没一个是有文化的，因为他们之中连脱稿演讲的能力都不具备，连脱稿回答记者的问题的能力都没有的人，还能写书。真搞不懂GitHub上面还有那么多仇恨抹黑美国的小粉红，大5毛。好歹都是翻过墙的人，难道连这点分辨是否的能力都没有吗？还是故意，还想给程序员洗脑。

还怀疑王沪宁有没有能力写书？等你自己有能力当上复旦大学的教授再来质疑吧。

**Comment by cn247365** [comment]
> 旦大学的教授再来质疑吧

7常委之一，在国内想做什么想要什么教授，博士头衔都可以给，习还是北大清华博士呢。牛逼去考个美国/日本/英国的国际一流大学的文凭试试。

**Comment by likeSo** [comment]
> > 旦大学的教授再来质疑吧
> 
> 7常委之一，在国内想做什么想要什么教授，博士头衔都可以给，习还是北大清华博士呢。牛逼去考个美国/日本/英国的国际一流大学的文凭试试。

“他有学历，那一定是他通过不法手段获取的，我不跟他比。”
“他竟然会写书？我不信，一定是瞎编的。”
好话歹话都让你™️说了，我帮你总结一下，您就是国际驰名的双标狗aka牧羊犬吧？
怎么滴，川普下台了瞌睡王上任了，你的工资又到位了？
我还是那句话，人家GitHub官方都没说话，你跳出来乱吠什么？讽刺我天朝官员的时候没人站出来说话，放本书你跳出来说不让放，好家伙，你替你远在大洋对岸的主子出征啊？
讲理吧你不行，戴高帽你是第一名啊。好好做个人吧，如果你还有点良知的话

**Comment by DDCHlsq** [comment]
> > 旦大学的教授再来质疑吧
> 
> 7常委之一，在国内想做什么想要什么教授，博士头衔都可以给，习还是北大清华博士呢。牛逼去考个美国/日本/英国的国际一流大学的文凭试试。

人家先做教授再破格提拔的，先搞清楚事实吧。而且最后一句话，欧美大学找关系的才最多，不然什么叫推荐信啊。提升一下你自己的水平吧，不然喷都喷不到点子上，被人笑话。
