### ISSUE TITLE
Epub Docx格式第8页

### ISSUE THREAD

**Issue by migsmiku** [zealotCE/AmericaOpposeAmerica#5]
“连美国学者都表示过在经济权力的差别是那么大，以致一个集团可以用非政治手段来决定另一个集团祸福的都发霉和，一种政治的民主就不可能发挥适当的功能。”

这一段看了看md文件里面发现应该是祸福的地方

**Comment by zealotCE** [comment]
是的，已修复epub版本的文字问题

**Comment by zealotCE** [comment]
> “连美国学者都表示过在经济权力的差别是那么大，以致一个集团可以用非政治手段来决定另一个集团祸福的都发霉和，一种政治的民主就不可能发挥适当的功能。”
> 
> 这一段看了看md文件里面发现应该是祸福的地方

感谢反馈
