### ISSUE TITLE
项目名字可能不太对

### ISSUE THREAD

**Issue by tzattack** [zealotCE/AmericaOpposeAmerica#6]
一般情况下反对应该是 Against，Oppose 是用来形容位置相对的。

**Comment by zealotCE** [comment]
你说的没错。我搞错了，但是由于时间太久导致我忘记了当时为什么用的这个名字。

**Comment by zealotCE** [comment]
> 一般情况下反对应该是 Against，Oppose 是用来形容位置相对的。

我回头补一下注释说明这个问题

**Comment by gaospecial** [comment]
github仓库改名之后不影响push，可以被自动重定向。

**Comment by zhiqwang** [comment]
> github仓库改名之后不影响push，可以被自动重定向。

也不影响外部链接的访问

**Comment by linesh-simplicity** [comment]
同建议直接改仓库名，不然分享出去的url还是含oppose，容易造成错误的阅读印象。

**Comment by luojunyuan** [comment]
可以参考[这里](https://docs.github.com/cn/free-pro-team@latest/github/administering-a-repository/renaming-a-repository)来为这个项目重命名

**Comment by luojunyuan** [comment]
这本书最近因为一些原因突然又引起关注了
我在知乎、哔哩哔哩、[外网](https://www.bloomberg.com/news/articles/2021-01-13/a-2-500-book-on-u-s-decline-is-suddenly-a-must-read-in-china)等网站都有看到，[v2](https://www.v2ex.com/t/744455)也有人引流过来

**Comment by zhiqwang** [comment]
沈逸[微博](https://m.weibo.com/1157864602/JD1Zg80YE)也转发Bloomberg的链接咯

**Comment by CRICKET107jrmoya** [comment]
美国反对美国. Republicans white house is cia director fired and gives up

**Comment by zealotCE** [comment]
> 美国反对美国. Republicans white house is cia director fired and gives up

这个项目原书中没有中文翻译，所以没有做调整。
另外，我这个名字是当时建立仓库用的，不是学术。并且，频繁改动名字不合适。所以，不做调整哈。
